version: 0.2

phases:
  build:
    commands:
      - dotnet test ./src/HelloTests/HelloTests.csproj
      - dotnet publish -c release -o ./build_output ./src/HelloWorldWebCore/HelloWorldWebCore.csproj
      - msbuild  ./src/HelloWorldWebCore/HelloWorldWebCore.csproj /t:Package /p:DeployIisAppPath="Default Web Site"
artifacts:
  files:
    - src/HelloWorldWebCore/build_output/*
    - appspec.yml
    - installApp.sh
