version: 0.2

phases:
  build:
    commands:
     - msbuild ./src/HelloWorldWebCore.sln /p:Configuration=Release /p:Platform="Any CPU" /t:Package /p:DeployIisAppPath="Default Web Site"
     - dotnet test ./src/HelloTests/HelloTests.csproj
     - dotnet publish -c release -o ./build_output ./src/HelloWorldWebCore/HelloWorldWebCore.csproj

artifacts:
  files:
    - src/HelloWorldWebCore/build_output/*
    - appspec.yml
    - installApp.sh
